#!/bin/bash

# https://github.com/fossgis-routing-server/osrm-backend
# http://project-osrm.org/docs/v5.23.0/api
wget http://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/foot.lua /data/thueringen-latest.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/thueringen-latest.osrm
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/thueringen-latest.osrm
# docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-contract /data/thueringen-latest.osrm
docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/thueringen-latest.osrm
# docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm ch /data/thueringen-latest.osrm

